- CHANGELOG.md
- README.md
- src/Engines/AlgoliaEngine.php
- tests/Features/WhereQueriesTest.php
This Pull Request adds Laravel Scout's Builder class adding support to complex where conditions.
The `where()` now supports `<`, `<=`, `=`, `!=`, `>=`, `>` operators:
```php
$models = Article::search('query')->where('views', '> 100'); // views > 100
$models = Article::search('query')->where('views <=', '100'); // views <= 100
$models = Article::search('query')->where('views', '100'); // views = 100
```
> [0.3] Adds support to complex where conditions

- composer.json
It seems that despite `"sort-packages": true,` config key, the packages have been added manually.
This PR ensures that the composer dependencies are properly sorted.
> Ensure that the composer dependencies are properly sorted.

- .gitignore
- src/Repositories/LocalSettingsRepository.php
- tests/Features/OptimizeCommandTest.php
- tests/TestCase.php
Added a setting to `config/scout.php` enabling Algolia's index settings to be stored in a configurable location. 
Closes #118
Documentation needs updating to include this new option.
There are no tests to update.
> Added configurable settings path

- src/Jobs/DeleteJob.php
- tests/Features/AggregatorTest.php
- tests/Features/SplittersTest.php
Hi @nunomaduro 
This fixes [142](https://github.com/algolia/scout-extended/issues/142). 
`unsearchable()` will now work on collections as well. Let me know if anything else is needed.
Thanks a lot!
> Fixes bug whereby a collection could not be made unsearchable.

- src/Jobs/UpdateJob.php
- src/Searchable/ModelsResolver.php
- tests/Features/SearchableTest.php
Hi @nunomaduro 
This PR fixes #154. I made the `$metadata` property public and used `Arr::except()` in the update job to remove those keys if it is present in the array. 
**Edit**: I also added a SearchableTest which validates a `searchable()` action without indexing the `_rankingInfo` and `_highlightResult` keys. Let me know if anything else is needed for this.
> Fixes 154 whereby _rankingInfo and _highlightResult were being indexed.

- src/Console/Commands/OptimizeCommand.php
- src/Engines/AlgoliaEngine.php
- src/Helpers/SearchableFinder.php
- src/Repositories/LocalSettingsRepository.php
- src/ScoutExtendedServiceProvider.php
- src/Searchable/Aggregator.php
Hi
PR adds support of Lumen #56. 
1. It replaces helpers that are incompatible with Lumen. Lumen supports limited [list](https://github.com/laravel/lumen-framework/blob/master/src/helpers.php) of `Illuminate\Foundation\helpers`. 
2. Helper class `SearchableFinder` uses `\Illuminate\Foundation\Application` as DI now. Lumen uses own extension of Container -  `Laravel\Lumen\Application`.  So I added `Illuminate\Container\Container` class as DI (not sure about it).
In spite of the fixes extra Lumen specific setup steps are still required. Maybe it is worth to add these steps to the documentation. Something like that:
Enable Eloquent and Facades if you plan to use it:
```php
// bootstrap/app.php:
$app->withFacades();
$app->withEloquent();
```
Bind path to the configuration directory with the …
> Lumen support

- src/Console/Commands/SyncCommand.php
This threw me a little.
`similar` means the settings resemble each other, but are not necessarily the same.
This change makes it clearer that the settings on the `local` and `remote` are actually equal to each other.
> Make wording clearer

- src/Searchable/Aggregator.php
Addition of internal tag on Aggregator's `searchable` and `unsearchable` methods
> Addition of internal tag

- src/Jobs/UpdateJob.php
- tests/Features/FlushCommandTest.php
- tests/Features/ImportCommandTest.php
- tests/Features/SearchableTest.php
- tests/laravel/app/EmptyItem.php
- tests/laravel/database/factories/EmptyItemFactory.php
- tests/laravel/database/migrations/2014_10_12_000003_create_empty_items_table.php
When looping through searchable models, skip any model that return searchable array as empty.
This will solve #192
> Fix empty searchable array got indexed when soft delete meta data is enabled.

- composer.json
This pull request adds the possibility of launch the test suite using `composer test`.
> chore: improves test suite launch from composer

- src/Helpers/SearchableFinder.php
- tests/Features/SearchableFinderTest.php
- tests/laravel/app/UnresolvableClass.php.stub
Fixes #213 
I think this is the best approach. I've also considered creating a `E_USER_NOTICE` but Laravel still catches that as a full error.
In my opinion, no errors should be thrown and the code should just ignore the non-imported classes.
Alternatively, there are 2 (perhaps slightly better) approaches:
1. Log a warning to the log file
2. Keep track of files not imported and send them back to the command, and log them as warnings to the command line.
That last one sounds nice but involves quite a bit of passing through the collection of files; not really clean.
> Ignore errors when requiring files for inspection

- composer.json
This fixes the `illuminate/contracts` version constraint.
> fix: illuminate/contracts dependency

- .circleci/config.yml
- composer.json
| Related Issue     | #256 
This updates the CircleCI config, which used the [incorrect variables](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables). This caused the key dealer to fail, resulting in API key errors. See [this PR](https://github.com/algolia/scout-extended/pull/256#issuecomment-738640759) to see the error in action.
> fix: use correct Circle variables

- .circleci/config.yml
- src/Settings/LocalFactory.php
| Related Issue     | Fix #258 
This sets all the required environment variables for properly using the API key dealer.
> fix: use correct variables for API key dealer

- .circleci/config.yml
- composer.json
- phpunit.xml.dist
| New feature?      | yes
| Related Issue     | /
Provide support on PHP 8.0.
I'll keep this PR in Draft until all dependencies can handle PHP 8.0
**Waiting for:**
> PHP 8.0 Support

- composer.json
- src/Helpers/SearchableFinder.php
- tests/Features/FlushCommandTest.php
- tests/Features/ImportCommandTest.php
- tests/laravel/composer.json
- tests/laravel/database/migrations/2014_10_12_000003_create_terms_table.php
- tests/laravel/modules/Taxonomy/Term.php
Enhance SearchableFinder to find searchable classes outside of `app/` directory.
This change enables scout-extended to work with non-typical Laravel projects that have models stored in directories outside of `app/`.  For example a project that uses the [laravel-modules](https://github.com/nWidart/laravel-modules) library.
* `SearchableFinder` uses config (if present) in `config/scout.php`.  The existing behaviour has not changed.  I'm unsure if this is the best approach as it requires the end user to add config that is not present in the template `scout.php`.
* Tests modified to test the discovery of models located in the `laravel/modules` directory.  All tests passing.
> Enhance SearchableFinder to find searchable classes outside of app/

- CONTRIBUTING.md
- phpstan.neon.dist
| Related Issue     | Fix #245 
This adds some documentation on running the unit tests locally to clarify the contribution process.
Edit: d1aba83 ensures that we temporarily ignore errors that PHPStan raises due to a bug. See [this PR comment](https://github.com/algolia/scout-extended/pull/265#issuecomment-783351989) for more details.
> chore: add documentation for local test suite

- phpstan.neon.dist
- src/Builder.php
- tests/Features/WhereQueriesTest.php
| Bug fix?          | Yes
| New feature?      | No
| Related Issue     | Fix #200 
This will add an empty condition to the whereIn method to make sure it'll add the condition only if the array is not empty. if it's empty it'll add a false condition to make sure the condition will stop ALL records from being returned.
Originally passing an empty array to `whereIn` resulted in ignoring the entire condition, this results in unexpected search results where a user might see more results than they should.
For example
```
// Returns all records matching the query ignores the id condition
// it'll return all results matching the search query and ignores completely the whereIn condition …
```
> [BUG] - empty whereIn array results in condition ignored

- src/Console/Commands/OptimizeCommand.php
- src/Console/Commands/SyncCommand.php
- src/Contracts/LocalSettingsRepositoryContract.php
- src/Repositories/LocalSettingsRepository.php
- src/ScoutExtendedServiceProvider.php
- src/Settings/Status.php
- src/Settings/Synchronizer.php
| Related Issue     | Fix #123
| Need Doc update   | not necessarily
We're working on a multi-tenant app and would like more fine-grained control over how config is stored. Since `LocalSettingsRepository` is `final`, we're not able to extend it to modify (see #222 for a previous attempt to make it extendable).
I respect the decision to keep everything `final`, so instead I propose creating a contract for the `LocalSettingsRepository`, so package users may bind their own implementation to the IoC.
Provides more control over local configuration storage, useful when dealing with multiple environments (see #123) or multi-tenant applications.
> Add LocalSettingsRepositoryContract

- src/ScoutExtendedServiceProvider.php
This moves the registration of our macros and commands to the `boot` method of our service provider, where they need to be [according to the Laravel documentation](https://laravel.com/docs/8.x/providers#the-boot-method). This fixes an issue that could occur where the commands from Scout took preference over the Scout Extended commands, even if we override them.
> fix: register macros and commands during boot

- composer.json
This PR uses the latest version of the PHP API client, which drops support for PHP < 7.2. The new release doesn't have any B-breaking changes.
> chore: update Algolia API client

- .circleci/config.yml
- CHANGELOG.md
- composer.json
| New feature?     | no
| BC breaks?       | yes
| Need Doc update  | no
Add support for laravel/scout 9.0
Drop support for older versions of Laravel (6.0, 7.0)
With this change you can use laravel/scout ^9.0
> Add support for Laravel Scout 9.0

- src/Jobs/UpdateJob.php
- tests/Features/Fixtures/ThreadSearchableTrait.php
- tests/Features/Fixtures/ThreadWithSearchableArrayOnTrait.php
- tests/Features/TransformersTest.php
| Bugfix?          | yes
| BC breaks?        | no
The `UpdateJob` class has a little trick that checks if the model has a `toSearchableArray` implementation, and if it doesn't, it will apply a generic transformation.
Given that every searchable model has to implement Laravel Scout's Searchable trait, the check logic had to be wrapped around that. A simple `method_exists` wouldn't cut it.
To solve this, this package was making sure that the definition of the method `toSearchableArray` was the actual model's class.
. . .
The problem with this implementation comes when you want to group behavior inside a trait (especially for big models).
At Studocu we usually do this, and it took us a …
> [Bugfix] Allow toSearchableArray on Traits

- CHANGELOG.md
- src/Builder.php
- tests/Features/BuilderTest.php
Adding optional filters to the query can now be done with the `whereOptional` builder helper. It is still also possible to use `with`.
| New feature?      | yes
| Related Issue     | no
| Need Doc update   | yes
A new `whereOptional` builder helper is introduced to add optional filters to a search.
Using the `with` helper to send optional parameters can be tedious when you have multiple of them - especially if they're conditional. With that Pull Request, it is now possible to use `whereOptional` for optional filters just like `where` can be used for filters. It also removes the necessity to build strings in the specific format Algolia expects, as it is done under the hood by the …
> Implement builder helper for optional filters

- .circleci/config.yml
This PR changes the Docker image used to run our tests. The current one in use will be deprecated by CircleCI.
> chore: use new CircleCI image

- src/Console/Commands/ReImportCommand.php
This force the queue to be disabled during a reimport. This allows us to reimport lots of records (1M+) without having to worry about race conditions (performing the `moveIndex` before all records have been imported).
We can disable the queue here as well because it's meant to improve performance during requests, but this script is never called during requests so we don't _have_ to queue the operations, especially since it can lead to issues when you have a big number of records.
> fix: force sync reimport

- src/Searchable/Aggregator.php
| Related Issue     | Fix #282 
This PR adds a change to circumvent the queue when using aggregators.
See #282
> fix: circumvent queue when using aggregators (Scout Extended v1)

- src/Searchable/Aggregator.php
| Related Issue     | Fix #282 
This PR adds a change to circumvent the queue when using aggregators.
See #282
> fix: circumvent queue when using aggregators

- CHANGELOG.md
- src/Engines/AlgoliaEngine.php
| New feature?      | yes
| Related Issue     | Fix #298
Adds a `lazyMap` method to the Algolia engine to fix #298. This PR is a band-aid solution—it doesn't actually implement any 'lazy' functionality the way Scout does, `lazyMap` behaves exactly the same as `map` and just returns a lazy collection, but at least now `lazyMap` will _work_ instead of returning no results.
See #298. `lazyMap` is not currently implemented, and because Scout Extended uses different result keys than Scout does, calling `lazyMap` when using Scout Extended always returns no results.
cc @DevinCodes
> Add `lazyMap` method to Algolia engine

- src/Searchable/Aggregator.php
- src/Searchable/AggregatorCollection.php
- tests/Features/AggregatorTest.php
| BC breaks?        | no
| Related Issue     | Fix #305
This PR adds an `unsearchable` method to Scout Extended's `AggregatorCollection` class. This ensures that any time an Aggregator is removed from search, it gets removed using the `queueRemoveFromSearch` method on itself or on the base `Aggregator` class it extends, _never_ the method in Scout's base `Searchable` trait.
The issue is demonstrated with a failing test in the first commit, the fix is included in the second commit and that test should then pass.
I also removed the manual re-registration of the Collection macros in the aggregator, since it's now unnecessary—for `searchable`, Scout Extended's …
> Fix Aggregator Collection macros being overwritten when other models boot

- src/Searchable/Aggregator.php
This fixes a bug introduced in the last release where macros for Aggregators were not registered, which causes issues when models in the aggregator don't have the `Searchable` trait.
> fix: register macros

- phpstan.neon.dist
- src/Jobs/DeleteJob.php
- tests/Features/AggregatorTest.php
- tests/Features/SplittersTest.php
- tests/Features/UnsearchableTest.php
| Related Issue     | Fix #311
| Need Doc update   | yes
This change is to account for the fact that the 'deleteBy' method has been deprecated on the new NeuralSearch infrastructure.
We have been advised of this by the Algolia support team and they have stated that it's a requirement in order to use the new infrastructure.
This update should also address the issue outlined in https://github.com/algolia/scout-extended/issues/311
> Refactored the DeleteJob to use 'deleteObjects' instead of 'deleteBy'

- composer.json
- phpstan.neon.dist
| Related Issue     | Fix #347, [#883](https://github.com/laravel/scout/issues/883), [#855](https://github.com/laravel/scout/issues/855)
Downgraded `laravel/scout` to version v10.11.5 in composer.json to resolve a conflict with the Algolia Search Client.
This change addresses compatibility issues between [Laravel Scout v10.11.6 (and newer)](https://packagist.org/packages/laravel/scout#v10.11.6) and recent versions Algolia Search Client, ensuring stable integration.
The proposed solution is to downgrade downgrade dependency [Laravel Scout to v10.11.5](https://packagist.org/packages/laravel/scout#v10.11.5).
- [Incompatible with …
> Fix conflict with Laravel/Scout v10.11.6 and newer

- composer.json
- phpstan.neon.dist
- src/Engines/AlgoliaEngine.php
| Related Issue     | Fix #347 
My change is backwards compatible and supports newer versions of laravel/scout by aliasing the proper extended class.
Laravel Scout created a v3 and v4 version of the Algolia Engine, and made the AlgoliaEngine class itself abstract. This was introduced in version 10.11.6 of laravel/scout.
A previous PR just ensured that scout would stay lower than `10.11.6`, but this change allows for newer versions. This will become more important in a few weeks when Laravel 12 is released and it requires a newer version of laravel scout than 10.11.5.
> Support newer versions of laravel scout

- src/Console/Commands/ReImportCommand.php
This ensures we don't force override some settings in case one of the nodes has a slight delay in indexing and the temporary index may not be present on that specific node yet.
> fix: check if index exists before force creating

- src/Searchable/AggregatorObserver.php
- tests/Features/AggregatorTest.php
| Related Issue     | Fix #285 and #301
Currently, the `deleted` and `forceDeleted` event handlers are disabled in `AggregatorObserver` if `disableSearchSyncing` has been set for an aggregator model. This should only disable the event handlers for the aggregator **models** and not the event handlers for aggregator **class** itself.  For this `disableSearchSyncing` should only be handled by the `ModelObserver` and not by the `AggregatorObserver` like it is currently implemented with the `saved` event handler in `ModelObserver` and `AggregatorObserver`.
Currently, if multiple models are used in one index by using an aggregator …
> Fix AggregatorObserver sync status
